name = "HadaMAG"
uuid = "7daef0c1-bc35-4833-8fb6-41d39c5c34f8"
authors = ["Jofre Vall√®s-Muns"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DelimitedFiles = "1.9.1"
Distributions = "0.25.120"
JLD2 = "0.5.13"
JuliaFormatter = "2.1.2"
LinearAlgebra = "1.10"
NPZ = "0.4.3"
Printf = "1.11.0"
Random = "1.10"
Statistics = "1.11.1"
julia = "1.10"
