name = "HadaMAG"
uuid = "82819514-a69d-403d-9fb3-9574bc69ff4e"
version = "0.1.0"
authors = ["Jofre Vall√®s-Muns"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastHadamardStructuredTransforms_jll = "3b5334fc-ad2e-52bb-943a-614153fa1c0c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
HadaMAGCUDAExt = "CUDA"
HadaMAGMPICUDAExt = ["MPI", "CUDA"]
HadaMAGMPIExt = "MPI"

[compat]
CUDA = "5"
DelimitedFiles = "1.9.1"
Distributions = "0.25.120"
FastHadamardStructuredTransforms_jll = "0.0.1"
JLD2 = "0.5.13"
JuliaFormatter = "2.1.2"
Libdl = "1.10.10"
LinearAlgebra = "1.10"
MPI = "0.20.22"
NPZ = "0.4.3"
Printf = "1.10"
Random = "1.10"
Statistics = "1.10"
julia = "1.10"
