name = "HadaMAG"
uuid = "7daef0c1-bc35-4833-8fb6-41d39c5c34f8"
authors = ["Jofre Vall√®s-Muns"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
JLD2 = "0.5.13"
LinearAlgebra = "1.11.0"
NPZ = "0.4.3"
Random = "1.11.0"
julia = "1.10"
